name: gcc-build-and-test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

 #   strategy:
 #     matrix:
 #       compiler: [gcc, clang]

    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@main

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ninja-build cmake
        sudo apt install g++ # Just in case

    - name: Set up compiler
      run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

    - name: Configure with CMake
      run: cmake -S . -B build -G "Ninja" build -Dcsvd_enable_tests=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build

    - name: Run CTest
      run: ctest --test-dir build --output-on-failure
